version: '3'

services:
    web-vulndb:
        image: nginx:stable-alpine
        container_name: web-vulndb
        volumes:
            - "./web-vulndb/www:/usr/share/nginx/html:ro"
            - "./web-vulndb/log:/var/log/nginx"
            - "./web-vulndb/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"

    php-vulndb:
        image: php:fpm-alpine
        container_name: php-vulndb
        volumes:
            - "./web-vulndb/api:/script:ro"
            - "./web-vulndb/data:/data"

